"""Write the playground examples (src/components/sepia/tokenizer/examples.ts) from the code index.

    python scripts/tokenizer/examples.py --code <LUSCA_DATA>/code

Each example is an unmodified excerpt (whole lines, common indentation removed) of a file in the
code index, with its repository, commit, path, line range and license. Only permissively or
copyleft-licensed files are used (no source-available or all-rights-reserved code).
"""

import argparse
import glob
import gzip
import json
import os
import textwrap

EXAMPLES = [
    {"id": "uniswap", "label": "Uniswap V2 · swap()", "lang": "solidity", "repo": "Uniswap/v2-core", "path": "contracts/UniswapV2Pair.sol", "start": "    function swap(uint amount0Out", "before": 1, "end": "    }\n"},
    {"id": "anchor", "label": "Anchor · swap_base_input", "lang": "rust", "repo": "raydium-io/raydium-cp-swap", "path": "programs/cp-swap/src/instructions/swap_base_input.rs", "start": "pub fn swap_base_input(", "lines": 34},
    {"id": "move", "label": "Sui Move · coin", "lang": "move", "repo": "MystenLabs/sui", "path": "crates/sui-framework/packages/sui-framework/sources/coin.move", "start": "/// Consume the coin `c` and add its value to `self`.", "lines": 25},
    {"id": "cairo", "label": "Cairo · ERC20 transfer", "lang": "cairo", "repo": "OpenZeppelin/cairo-contracts", "path": "packages/token/src/erc20/erc20.cairo", "start": "        /// Moves `amount` tokens from the caller's token balance to `to`.", "lines": 32},
]

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "src", "components", "sepia", "tokenizer", "examples.ts")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--code", required=True)
    a = ap.parse_args()
    want = {(e["repo"], e["path"]) for e in EXAMPLES}
    found = {}
    for f in glob.glob(os.path.join(a.code, "*.jsonl.gz")):
        with gzip.open(f, "rt", encoding="utf-8") as fh:
            for line in fh:
                r = json.loads(line)
                if (r["repo"], r["path"]) in want:
                    found[(r["repo"], r["path"])] = r
    out = []
    for e in EXAMPLES:
        r = found[(e["repo"], e["path"])]
        text = r["text"].replace("\r\n", "\n")
        lines = text.split("\n")
        start = next(i for i, l in enumerate(lines) if l.startswith(e["start"])) - e.get("before", 0)
        if "lines" in e:
            end = start + e["lines"]
        else:
            end = next(i for i in range(start + 1, len(lines)) if lines[i] + "\n" == e["end"]) + 1
        body = textwrap.dedent("\n".join(lines[start:end])).rstrip() + "\n"
        out.append({
            "id": e["id"], "label": e["label"], "lang": e["lang"], "repo": r["repo"], "commit": r["commit"],
            "path": r["path"], "lines": [start + 1, end], "license": r["license"], "code": body,
        })
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by scripts/tokenizer/examples.py from the protocol code index. Do not edit.\n")
        f.write("// Unmodified excerpts (whole lines, common indentation removed); license and source per entry.\n\n")
        f.write("export interface TokenizerExample { id: string; label: string; lang: string; repo: string; commit: string; path: string; lines: [number, number]; license: string; code: string }\n\n")
        f.write("export const EXAMPLES: TokenizerExample[] = " + json.dumps(out, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {OUT}: " + ", ".join(f"{x['id']} {len(x['code'])} chars" for x in out))


if __name__ == "__main__":
    main()
