"""Write the playground examples (src/components/sepia/tokenizer/examples.ts) from the code index.

    python scripts/tokenizer/examples.py --code <LUSCA_DATA>/code

Each example is an unmodified excerpt (whole lines, common indentation removed) of a file in the
code index, with its repository, commit, path, line range and license. Only permissively or
copyleft-licensed files are used (no source-available or all-rights-reserved code).

Every example must come from the held-out evaluation split (data-manifest.json eval[lang].files),
so the playground never shows a file the tokenizer was trained on; the script refuses otherwise.
The examples were chosen for being recognisable protocol code, before their token counts were
looked at.
"""

import argparse
import glob
import gzip
import json
import os
import textwrap

EXAMPLES = [
    {"id": "solmate", "label": "Solmate ERC4626 · deposit()", "lang": "solidity", "repo": "transmissions11/solmate", "path": "src/tokens/ERC4626.sol", "start": "    function deposit(uint256 assets, address receiver)", "lines": 26},
    {"id": "openbook", "label": "OpenBook v2 · Anchor instruction", "lang": "rust", "repo": "openbook-dex/openbook-v2", "path": "programs/openbook-v2/src/instructions/cancel_all_and_place_orders.rs", "start": "#[allow(clippy::too_many_arguments)]", "lines": 36},
    {"id": "deepbook", "label": "DeepBook · math.move", "lang": "move", "repo": "MystenLabs/deepbookv3", "path": "packages/deepbook/sources/helper/math.move", "start": "/// Divide two floating numbers.", "lines": 39},
    {"id": "cairo", "label": "OpenZeppelin Cairo · royalty_info", "lang": "cairo", "repo": "OpenZeppelin/cairo-contracts", "path": "packages/token/src/common/erc2981/erc2981.cairo", "start": "    #[embeddable_as(ERC2981Impl)]", "lines": 35},
]

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "src", "components", "sepia", "tokenizer", "examples.ts")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--code", required=True)
    a = ap.parse_args()
    manifest = json.load(open(os.path.join(ROOT, "scripts", "tokenizer", "data-manifest.json"), encoding="utf-8"))
    for e in EXAMPLES:
        held = {(f["repo"], f["path"]) for f in manifest["eval"][e["lang"]]["files"]}
        if (e["repo"], e["path"]) not in held:
            raise SystemExit(f"{e['id']}: {e['repo']}/{e['path']} is not in the held-out {e['lang']} split")
    want = {(e["repo"], e["path"]) for e in EXAMPLES}
    found = {}
    for f in glob.glob(os.path.join(a.code, "*.jsonl.gz")):
        with gzip.open(f, "rt", encoding="utf-8") as fh:
            for line in fh:
                r = json.loads(line)
                if (r["repo"], r["path"]) in want:
                    found[(r["repo"], r["path"])] = r
    out = []
    for e in EXAMPLES:
        r = found[(e["repo"], e["path"])]
        text = r["text"].replace("\r\n", "\n")
        lines = text.split("\n")
        start = next(i for i, l in enumerate(lines) if l.startswith(e["start"])) - e.get("before", 0)
        if "lines" in e:
            end = start + e["lines"]
        else:
            end = next(i for i in range(start + 1, len(lines)) if lines[i] + "\n" == e["end"]) + 1
        body = textwrap.dedent("\n".join(lines[start:end])).rstrip() + "\n"
        out.append({
            "id": e["id"], "label": e["label"], "lang": e["lang"], "repo": r["repo"], "commit": r["commit"],
            "path": r["path"], "lines": [start + 1, end], "license": r["license"], "split": "held-out", "code": body,
        })
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by scripts/tokenizer/examples.py from the protocol code index. Do not edit.\n")
        f.write("// Unmodified excerpts (whole lines, common indentation removed); license and source per entry.\n\n")
        f.write("export interface TokenizerExample { id: string; label: string; lang: string; repo: string; commit: string; path: string; lines: [number, number]; license: string; split: 'held-out'; code: string }\n\n")
        f.write("export const EXAMPLES: TokenizerExample[] = " + json.dumps(out, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {OUT}: " + ", ".join(f"{x['id']} {len(x['code'])} chars" for x in out))


if __name__ == "__main__":
    main()
