r"""Write shared/sepia1/unicode-classes.ts: the exact \p{L} and \p{N} sets of the Python tokenizer.

    python scripts/tokenizer/unicode_classes.py

The SEPIA-1 pre-tokenizer (spec.py) uses \p{L} (letters) and \p{N} (numbers). Hugging Face
`tokenizers` compiles them with Oniguruma, whose Unicode tables are fixed when the library is
built; a JavaScript engine compiles them with its own, newer tables (Node 24 knows Unicode 16).
Characters added in between (CJK Extension H/I, Kawi, Nag Mundari, Garay, ...) would then be split
differently in the browser than in Python.

So the TypeScript encoder does not use \p{...} at all: it substitutes the code-point ranges written
here, which are measured from the installed `tokenizers` by running its own regex over every code
point (U+0000..U+10FFFF without surrogates). The result depends only on the tokenizers version
recorded in the file header, not on the browser.
"""

import os

import tokenizers
from tokenizers import Regex, pre_tokenizers

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "shared", "sepia1", "unicode-classes.ts")


def members(prop):
    """Code points matched by \\p{prop} in tokenizers' regex engine."""
    split = pre_tokenizers.Split(Regex("\\p{" + prop + "}"), behavior="removed")
    out = []
    step = 1 << 15
    for base in range(0, 0x110000, step):
        cps = [c for c in range(base, min(base + step, 0x110000)) if not 0xD800 <= c <= 0xDFFF]
        s = "".join(map(chr, cps))
        keep = bytearray(len(cps))  # 1 = not matched (left in a piece)
        for _, (a, b) in split.pre_tokenize_str(s):
            for i in range(a, b):
                keep[i] = 1
        out.extend(cp for cp, k in zip(cps, keep) if not k)
    return out


def ranges(cps):
    rs = []
    for c in cps:
        if rs and rs[-1][1] == c - 1:
            rs[-1][1] = c
        else:
            rs.append([c, c])
    return rs


def js_class(rs):
    def u(c):
        return "\\\\u{%X}" % c

    return "".join(u(a) if a == b else f"{u(a)}-{u(b)}" for a, b in rs)


def main():
    L = members("L")
    N = members("N")
    # spot checks with single characters (independent of the batching above)
    for prop, cps in (("L", L), ("N", N)):
        split = pre_tokenizers.Split(Regex("\\p{" + prop + "}"), behavior="removed")
        s = set(cps)
        for c in list(range(0, 0x3000, 7)) + [0x10000, 0x10D40, 0x10D4A, 0x11F04, 0x1E4D0, 0x1E4F0, 0x2EBF0, 0x31350, 0x323AF, 0x1CCF0]:
            if 0xD800 <= c <= 0xDFFF:
                continue
            matched = split.pre_tokenize_str(chr(c)) == []
            assert matched == (c in s), (prop, hex(c))
    rl, rn = ranges(L), ranges(N)
    lines = [
        "// Generated by scripts/tokenizer/unicode_classes.py. Do not edit.",
        f"// \\p{{L}} and \\p{{N}} exactly as Hugging Face tokenizers {tokenizers.__version__} (Oniguruma) matches them,",
        "// measured over every code point, so the browser encoder does not depend on the JavaScript",
        "// engine's Unicode version. Used inside a RegExp character class with the u flag.",
        f"// \\p{{L}}: {len(L):,} code points in {len(rl)} ranges; \\p{{N}}: {len(N):,} code points in {len(rn)} ranges.",
        "",
        f"export const ONIG_TOKENIZERS_VERSION = '{tokenizers.__version__}'",
        f"export const ONIG_L = '{js_class(rl)}'",
        f"export const ONIG_N = '{js_class(rn)}'",
        "",
    ]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: L {len(L)} cps / {len(rl)} ranges, N {len(N)} cps / {len(rn)} ranges")


if __name__ == "__main__":
    main()
