// Which files of a repository archive become training text.
//
// Kept: .sol .vy .rs .move .cairo, .md docs/specs, Anchor IDL .json; .go only for cosmos / bitcoin
// repositories (or a repo that opts in), .cpp/.h only for bitcoin, .ts only under sdk/ or test
// directories, .py only for repositories that opt in (consensus specs).
// Skipped: vendored / build directories, generated files, files over 200 KB (up to 640 KB for files
// an allowlist entry names in `largeFiles`), binaries, lockfiles.

import type { RepoSpec } from './repos.ts'
import { isLicenseFile } from './licenses.ts'

export const MAX_FILE_BYTES = 200 * 1024
/** Limit for the files an allowlist entry names in `largeFiles`: core logic that runs past 200 KB (validation.cpp, bank.rs, …). */
export const LARGE_FILE_BYTES = 640 * 1024

/** Size limit for the file at `rel` (path relative to the repository root). */
export function fileLimit(rel: string, spec: Pick<RepoSpec, 'largeFiles'>): number {
  return spec.largeFiles?.includes(rel) ? LARGE_FILE_BYTES : MAX_FILE_BYTES
}

/** Largest body the tar reader buffers for this repository. */
export function bodyLimit(spec: Pick<RepoSpec, 'largeFiles'>): number {
  return spec.largeFiles?.length ? LARGE_FILE_BYTES : MAX_FILE_BYTES
}

/** Directory names never descended into (unless an includePath names them explicitly). */
const SKIP_DIRS = new Set([
  'node_modules',
  'target',
  'lib', // forge / git submodule dependencies
  'out',
  'artifacts',
  'cache',
  'typechain',
  'typechain-types',
  'build',
  'dist',
  'coverage',
  'broadcast',
  'deployments',
  'vendor',
  'third_party',
  'third-party',
  'external',
  'fixtures',
  '__pycache__',
  '.git',
  '.github',
  '.vscode',
  '.idea',
  '.cargo',
  '.yarn',
  '.changeset',
  '.husky',
])

const SKIP_NAMES = /^(changelog|code_of_conduct|contributing|security|pull_request_template|issue_template|codeowners|authors|maintainers)(\.[\w-]+)*$/i

const GENERATED = /\b(?:auto-?generated|autogenerated|do not edit|code generated by|@generated|this file (?:was|is|has been) (?:automatically |auto-)?generated|generated (?:automatically )?by (?:the )?(?:typechain|abigen|protoc|anchor|codama|kinobi|solita|shank|wasm-bindgen|cbindgen|bindgen))\b/i

export type Lang = 'solidity' | 'vyper' | 'rust' | 'move' | 'cairo' | 'go' | 'cpp' | 'typescript' | 'python' | 'markdown' | 'idl'

/** Does `rel` (path relative to the repo root) fall under one of the include prefixes? '*' matches one segment. */
export function matchesInclude(rel: string, includePaths: string[] | undefined): boolean {
  if (!includePaths || includePaths.length === 0) return true
  const segs = rel.split('/')
  outer: for (const inc of includePaths) {
    const pat = inc.replace(/^\.?\/+/, '').replace(/\/+$/, '').split('/').filter(Boolean)
    if (pat.length === 0) return true
    if (pat.length > segs.length) continue
    for (let i = 0; i < pat.length; i++) if (pat[i] !== '*' && pat[i] !== segs[i]) continue outer
    return true
  }
  return false
}

/** The include prefix that covers `rel` (segments), to allow skip-listed names it spells out. */
function coveredSegments(rel: string, includePaths: string[] | undefined): number {
  if (!includePaths) return 0
  const segs = rel.split('/')
  let best = 0
  outer: for (const inc of includePaths) {
    const pat = inc.replace(/^\.?\/+/, '').replace(/\/+$/, '').split('/').filter(Boolean)
    if (pat.length > segs.length) continue
    for (let i = 0; i < pat.length; i++) if (pat[i] !== '*' && pat[i] !== segs[i]) continue outer
    best = Math.max(best, pat.length)
  }
  return best
}

/** Path-only checks: include prefixes and skipped directories. */
export function pathInScope(rel: string, spec: Pick<RepoSpec, 'includePaths' | 'excludePaths'>): boolean {
  if (!matchesInclude(rel, spec.includePaths)) return false
  if (spec.excludePaths && spec.excludePaths.length && matchesInclude(rel, spec.excludePaths)) return false
  const segs = rel.split('/')
  const from = coveredSegments(rel, spec.includePaths)
  for (let i = from; i < segs.length - 1; i++) {
    const s = segs[i]
    if (SKIP_DIRS.has(s.toLowerCase())) return false
  }
  return true
}

/**
 * Can a LICENSE file in directory `dir` (relative, '' = root) apply to kept files? It must not sit
 * in a skipped / excluded directory, and with includePaths it must lie inside one of them or above one.
 */
export function licenseDirInScope(dir: string, spec: Pick<RepoSpec, 'includePaths' | 'excludePaths'>): boolean {
  if (dir === '') return true
  const segs = dir.split('/')
  const probe = `${dir}/x`
  if (spec.excludePaths && spec.excludePaths.length && matchesInclude(probe, spec.excludePaths)) return false
  const from = coveredSegments(probe, spec.includePaths)
  for (let i = from; i < segs.length; i++) if (SKIP_DIRS.has(segs[i].toLowerCase())) return false
  if (!spec.includePaths || spec.includePaths.length === 0) return true
  return spec.includePaths.some((inc) => {
    const pat = inc.replace(/^\.?\/+/, '').replace(/\/+$/, '').split('/').filter(Boolean)
    const n = Math.min(pat.length, segs.length)
    for (let i = 0; i < n; i++) if (pat[i] !== '*' && pat[i] !== segs[i]) return false
    return true
  })
}

/** Language of a file in this repository, or null when its type is not kept. */
export function langOf(rel: string, spec: Pick<RepoSpec, 'ecosystem' | 'langs'>): Lang | null {
  const segs = rel.split('/')
  const base = segs[segs.length - 1]
  if (SKIP_NAMES.test(base) || isLicenseFile(base)) return null
  if (/\.min\.\w+$/i.test(base)) return null
  const dot = base.lastIndexOf('.')
  if (dot <= 0) return null
  const ext = base.slice(dot + 1).toLowerCase()
  const extra = spec.langs ?? []
  switch (ext) {
    case 'sol':
      return 'solidity'
    case 'vy':
    case 'vyi':
      return 'vyper'
    case 'rs':
      return 'rust'
    case 'move':
      return 'move'
    case 'cairo':
      return 'cairo'
    case 'md':
    case 'mdx':
      return 'markdown'
    case 'go':
      if (/\.(pb|pb\.gw|pulsar)\.go$/i.test(base)) return null
      return spec.ecosystem === 'cosmos' || spec.ecosystem === 'bitcoin' || extra.includes('go') ? 'go' : null
    case 'cpp':
    case 'cc':
    case 'h':
    case 'hpp':
      return spec.ecosystem === 'bitcoin' || extra.includes('cpp') ? 'cpp' : null
    case 'py':
      return extra.includes('python') ? 'python' : null
    case 'ts': {
      if (base.endsWith('.d.ts')) return null
      const lower = segs.map((s) => s.toLowerCase())
      if (lower.includes('sdk')) return 'typescript'
      const isTest = lower.some((s) => s === 'test' || s === 'tests' || s === '__tests__') || /\.(test|spec)\.ts$/i.test(base)
      return isTest && spec.ecosystem !== 'infra' ? 'typescript' : null
    }
    case 'json': {
      const lower = segs.map((s) => s.toLowerCase())
      return lower.includes('idl') || lower.includes('idls') || /idl/i.test(base) ? 'idl' : null
    }
    default:
      return null
  }
}

/** Content checks on the decoded text. Returns a reason when the file must be skipped. */
export function contentReject(text: string, lang: Lang): string | null {
  const head = text.length > 1500 ? text.slice(0, 1500) : text
  if (GENERATED.test(head)) return 'generated'
  if (text.indexOf('\0') >= 0) return 'binary'
  // Embedded bytecode / minified blobs: one very long line is not code anyone reads.
  let start = 0
  while (start < text.length) {
    let nl = text.indexOf('\n', start)
    if (nl < 0) nl = text.length
    if (nl - start > 5000) return 'long-line'
    start = nl + 1
  }
  if (lang === 'idl' && !/"instructions"\s*:/.test(text)) return 'not-idl'
  if (text.trim().length === 0) return 'empty'
  return null
}

const utf8 = new TextDecoder('utf-8', { fatal: true })

/** Decode UTF-8 strictly and normalise newlines; null for binary / invalid text. */
export function decodeText(body: Buffer): string | null {
  // NUL in the first 8 KB → binary
  const probe = body.length > 8192 ? body.subarray(0, 8192) : body
  if (probe.includes(0)) return null
  let s: string
  try {
    s = utf8.decode(body)
  } catch {
    return null
  }
  if (s.charCodeAt(0) === 0xfeff) s = s.slice(1)
  return s.replace(/\r\n?/g, '\n')
}
