// Allowlist of the protocol code index: landmark protocols and core infrastructure across
// ecosystems (EVM, Solana, Move, Cairo, Cosmos, Bitcoin, clients / VMs, security research).
// No memecoins, launchpads or token clones. Quality over volume.
//
// Licenses are recorded, never used to exclude (owner decision: SEPIA-1 learns from the code; it
// does not redistribute it). `license` is the SPDX expression of the root LICENSE file at `ref`
// (LicenseRef-* for project licenses, 'none' when the repository has no license file); per-file SPDX
// headers are recorded by the engine. A repository is left out only if it is not public or its
// license / README explicitly forbids machine-learning training (none of the entries below does).
//
// Verified 2026-10-05 without the GitHub API: branches and tags from the git ref advertisement
// (`git ls-remote`), license text and include paths from the codeload archive / raw files at that
// ref.
//
// Order is priority: the size cap (LUSCA_CODE_MAX_MB) cuts from the end of the list, so the list is
// ordered by tier across ecosystems — core landmark code of every ecosystem first (EVM, Solana,
// clients / VMs, Move, Cairo, Cosmos, then Solana / Move / Cairo / Bitcoin / cross-chain protocols),
// then more EVM protocols, then security corpora and reference programs (DeFiHackLabs, the largest
// and most templated, last among them), then specification text (EIPs, ERCs).
//
// Ref policy: the large monorepos are pinned to the release branch or tag of the code that is
// deployed (sui 'framework/mainnet', aptos 'mainnet', agave v4.3, bitcoin v31.1, osmosis v31.0.3,
// anchor v1.2.0, optimism op-contracts/v8.0.0, nitro-contracts v3.2.0, cosmos-sdk release/v0.55.x),
// not their development heads: no unreleased code, and an unchanged pin resolves to the same commit,
// so the weekly refresh does not download the archive again. Moving a pin is a deliberate edit of
// this file. ibc-go tracks 'main' because its release branches carry no docs/ tree. Smaller
// repositories track their default branch.
//
// Estimated from per-file listings of each archive run through filters.ts: 110 repositories,
// ≈ 18.5k files, ≈ 139 MB of text, ≈ 28–31 MB of gzip shards (measured 5–6x on code, 3.6x on
// markdown). Three archives are large: MystenLabs/sui ≈ 87 MB, osmosis-labs/osmosis ≈ 94 MB and
// otter-sec/anchor ≈ 76 MB compressed (within the engine's 120 MB per-archive limit). Files over
// 200 KB are dropped unless an entry names them in `largeFiles` (kept up to 640 KB).

import type { LicenseTier } from '../../shared/codebase.ts'

export type Ecosystem = 'evm' | 'solana' | 'move' | 'cairo' | 'cosmos' | 'bitcoin' | 'infra'
export type Category =
  | 'dex'
  | 'lending'
  | 'stablecoin'
  | 'staking'
  | 'bridge-rollup'
  | 'account-abstraction'
  | 'wallet'
  | 'token-standard'
  | 'oracle'
  | 'governance'
  | 'client-vm'
  | 'framework'
  | 'security'

export interface RepoSpec {
  repo: string
  ecosystem: Ecosystem
  category: Category
  ref: string
  license: string
  tier: LicenseTier
  includePaths?: string[]
  excludePaths?: string[]
  langs?: ('go' | 'cpp' | 'python')[]
  /**
   * Files (exact paths from the repository root) kept up to 640 KB instead of 200 KB: core logic
   * that runs long (Bitcoin Core validation.cpp, the Agave bank, the Token-2022 processor). They must
   * also fall under includePaths; the generated / long-line checks still apply.
   */
  largeFiles?: string[]
  note?: string
}

export const REPOS: RepoSpec[] = [
  // ─── EVM: landmark protocols ──────────────────────────────────────────────
  {
    repo: 'Uniswap/v2-core',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'master',
    license: 'GPL-3.0',
    tier: 'copyleft',
    note: 'Constant-product AMM pair and factory.',
  },
  {
    repo: 'Uniswap/v2-periphery',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'master',
    license: 'GPL-3.0',
    tier: 'copyleft',
    note: 'Router and library for v2 pairs.',
  },
  {
    repo: 'Uniswap/v3-core',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'BUSL-1.1',
    tier: 'source-available',
    excludePaths: ['audits'],
    note: 'Concentrated liquidity pools, tick math. BUSL change date (2023-04-01) has passed; the change license is GPL-2.0-or-later.',
  },
  {
    repo: 'Uniswap/v3-periphery',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'GPL-2.0-or-later',
    tier: 'copyleft',
    note: 'NonfungiblePositionManager, SwapRouter, quoter and libraries.',
  },
  {
    repo: 'Uniswap/v4-core',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'BUSL-1.1 AND MIT',
    tier: 'source-available',
    note: 'Singleton PoolManager, hooks, flash accounting. No root LICENSE file; SPDX headers: BUSL-1.1 core, MIT libraries and interfaces.',
  },
  {
    repo: 'Uniswap/v4-periphery',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'MIT',
    tier: 'permissive',
    note: 'PositionManager, V4Router, hook base contracts.',
  },
  {
    repo: 'Uniswap/permit2',
    ecosystem: 'evm',
    category: 'token-standard',
    ref: 'main',
    license: 'MIT',
    tier: 'permissive',
    note: 'Signature-based token approvals and transfers.',
  },
  {
    repo: 'Uniswap/universal-router',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'GPL-3.0-or-later',
    tier: 'copyleft',
    note: 'Command-encoded router across v2 / v3 / v4 and NFT markets.',
  },
  {
    repo: 'OpenZeppelin/openzeppelin-contracts',
    ecosystem: 'evm',
    category: 'framework',
    ref: 'master',
    license: 'MIT',
    tier: 'permissive',
    includePaths: ['contracts', 'docs', 'README.md', 'GUIDELINES.md'],
    excludePaths: ['contracts/mocks'],
    note: 'Reference implementations of ERC standards, access control, governance, proxies, utilities.',
  },
  {
    repo: 'aave-dao/aave-v3-origin',
    ecosystem: 'evm',
    category: 'lending',
    ref: 'main',
    license: 'BUSL-1.1',
    tier: 'source-available',
    includePaths: ['src/contracts', 'docs', 'README.md'],
    excludePaths: ['src/contracts/mocks'],
    note: 'Aave v3.x pool, tokenization, interest-rate and configuration logic (successor of aave-v3-core). BUSL-1.1 (Aave v3.7); change date 2027-03-06 or the v37.aavelicense.eth record; change license MIT.',
  },
  {
    repo: 'aave/protocol-v2',
    ecosystem: 'evm',
    category: 'lending',
    ref: 'master',
    license: 'AGPL-3.0',
    tier: 'copyleft',
    includePaths: ['contracts', 'README.md'],
    excludePaths: ['contracts/mocks'],
    note: 'Aave v2 lending pool, aTokens, debt tokens.',
  },
  {
    repo: 'compound-finance/compound-protocol',
    ecosystem: 'evm',
    category: 'lending',
    ref: 'master',
    license: 'BSD-3-Clause',
    tier: 'permissive',
    note: 'Compound v2: cTokens, Comptroller, interest-rate models, Governor Bravo.',
  },
  {
    repo: 'compound-finance/comet',
    ecosystem: 'evm',
    category: 'lending',
    ref: 'main',
    license: 'BUSL-1.1',
    tier: 'source-available',
    includePaths: ['contracts', 'README.md', 'SPEC.md'],
    excludePaths: ['contracts/test', 'contracts/vendor'],
    note: 'Compound III single-borrow-asset markets. BUSL change date (2025-12-31) has passed; the change license is GPL-2.0-or-later.',
  },
  {
    repo: 'sky-ecosystem/dss',
    ecosystem: 'evm',
    category: 'stablecoin',
    ref: 'master',
    license: 'AGPL-3.0-or-later',
    tier: 'copyleft',
    note: 'Multi-collateral Dai core: Vat, Jug, Cat / Dog, Clip, Vow, Pot (formerly makerdao/dss).',
  },
  {
    repo: 'sky-ecosystem/dss-psm',
    ecosystem: 'evm',
    category: 'stablecoin',
    ref: 'master',
    license: 'AGPL-3.0-or-later',
    tier: 'copyleft',
    note: 'Peg Stability Module (formerly makerdao/dss-psm).',
  },
  {
    repo: 'lidofinance/core',
    ecosystem: 'evm',
    category: 'staking',
    ref: 'master',
    license: 'GPL-3.0',
    tier: 'copyleft',
    // project lib/ directories are named explicitly: the engine skips lib/ (forge dependencies) otherwise
    includePaths: ['contracts', 'contracts/common/lib', 'contracts/0.4.24/lib', 'contracts/0.8.9/lib', 'contracts/0.8.25/vaults/lib', 'docs', 'README.md'],
    note: 'Lido stETH, staking router, node operator registry, accounting oracle, staking vaults.',
  },
  {
    repo: 'curvefi/curve-contract',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'master',
    license: 'LicenseRef-All-Rights-Reserved',
    tier: 'source-available',
    includePaths: ['contracts', 'README.md'],
    excludePaths: ['contracts/testing'],
    note: 'Original StableSwap pools and templates (Vyper). LICENSE: published for informational purposes, all rights reserved.',
  },
  {
    repo: 'curvefi/stableswap-ng',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'LicenseRef-All-Rights-Reserved',
    tier: 'source-available',
    includePaths: ['contracts/main', 'README.md'],
    note: 'StableSwap NG plain and meta pools, factory, math (Vyper). LICENSE: all rights reserved.',
  },
  {
    repo: 'curvefi/tricrypto-ng',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'LicenseRef-All-Rights-Reserved',
    tier: 'source-available',
    includePaths: ['contracts/main', 'README.md'],
    note: 'Cryptoswap (tricrypto) pools, math and factory (Vyper). LICENSE: all rights reserved.',
  },
  {
    repo: 'curvefi/curve-stablecoin',
    ecosystem: 'evm',
    category: 'stablecoin',
    ref: 'master',
    license: 'LicenseRef-All-Rights-Reserved',
    tier: 'source-available',
    includePaths: ['curve_stablecoin', 'README.md'],
    excludePaths: ['curve_stablecoin/testing'],
    note: 'crvUSD: LLAMMA, controllers, monetary policies, LlamaLend (Vyper). LICENSE: all rights reserved.',
  },
  {
    repo: 'balancer/balancer-v2-monorepo',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'master',
    license: 'GPL-3.0-or-later',
    tier: 'copyleft',
    includePaths: ['pkg/*/contracts', 'pkg/*/contracts/lib', 'README.md'],
    excludePaths: ['pkg/*/contracts/test'],
    note: 'Balancer v2 Vault, weighted / stable / linear pools, liquidity mining.',
  },
  {
    repo: 'balancer/balancer-v3-monorepo',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'GPL-3.0-or-later',
    tier: 'copyleft',
    includePaths: ['pkg/*/contracts', 'pkg/*/contracts/lib', 'README.md'],
    excludePaths: ['pkg/*/contracts/test'],
    note: 'Balancer v3 Vault, hooks, weighted / stable / Gyro pools.',
  },
  {
    repo: 'morpho-org/morpho-blue',
    ecosystem: 'evm',
    category: 'lending',
    ref: 'main',
    license: 'GPL-2.0-or-later',
    tier: 'copyleft',
    note: 'Isolated lending markets in one immutable contract; Certora specs.',
  },
  {
    repo: 'morpho-org/metamorpho',
    ecosystem: 'evm',
    category: 'lending',
    ref: 'main',
    license: 'GPL-2.0-or-later',
    tier: 'copyleft',
    note: 'ERC-4626 vaults allocating across Morpho Blue markets.',
  },
  {
    repo: 'safe-fndn/safe-smart-account',
    ecosystem: 'evm',
    category: 'wallet',
    ref: 'main',
    license: 'LGPL-3.0-only',
    tier: 'copyleft',
    includePaths: ['contracts', 'docs', 'README.md'],
    excludePaths: ['contracts/test'],
    note: 'Safe multisig smart account, modules, guards, fallback handlers (formerly safe-global).',
  },
  {
    repo: 'eth-infinitism/account-abstraction',
    ecosystem: 'evm',
    category: 'account-abstraction',
    ref: 'develop',
    license: 'GPL-3.0',
    tier: 'copyleft',
    note: 'ERC-4337 EntryPoint, reference accounts and paymasters.',
  },
  {
    repo: 'Vectorized/solady',
    ecosystem: 'evm',
    category: 'framework',
    ref: 'main',
    license: 'MIT',
    tier: 'permissive',
    includePaths: ['src', 'docs', 'README.md'],
    note: 'Gas-optimized Solidity / assembly library: tokens, accounts, math, signatures.',
  },
  {
    repo: 'transmissions11/solmate',
    ecosystem: 'evm',
    category: 'framework',
    ref: 'main',
    license: 'AGPL-3.0-only AND MIT',
    tier: 'copyleft',
    note: 'Minimal Solidity building blocks. LICENSE defers to per-file SPDX headers (AGPL-3.0-only, MIT).',
  },
  {
    repo: 'foundry-rs/forge-std',
    ecosystem: 'evm',
    category: 'framework',
    ref: 'master',
    license: 'MIT OR Apache-2.0',
    tier: 'permissive',
    note: 'Foundry standard library: Test, Vm cheatcodes, StdInvariant.',
  },

  // ─── Solana: core programs and frameworks ─────────────────────────────────
  {
    repo: 'solana-program/token',
    ecosystem: 'solana',
    category: 'token-standard',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['program', 'interface', 'pinocchio', 'README.md'],
    note: 'SPL Token program and interface, plus the p-token (pinocchio) rewrite.',
  },
  {
    repo: 'solana-program/token-2022',
    ecosystem: 'solana',
    category: 'token-standard',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['program', 'interface', 'confidential', 'README.md'],
    largeFiles: ['program/src/processor.rs'],
    note: 'Token-2022 with extensions (transfer hooks, fees, confidential transfers).',
  },
  {
    repo: 'solana-program/associated-token-account',
    ecosystem: 'solana',
    category: 'token-standard',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['program', 'interface', 'pinocchio', 'README.md'],
    note: 'Associated Token Account program.',
  },
  {
    repo: 'otter-sec/anchor',
    ecosystem: 'solana',
    category: 'framework',
    ref: 'v1.2.0',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['lang', 'spl', 'idl', 'tests/*/programs', 'docs/content/docs', 'README.md'],
    note: 'Anchor framework: account constraints, derive macros, IDL (coral-xyz/anchor now redirects here). Release tag v1.2.0. Archive is ~76 MB compressed.',
  },
  {
    repo: 'solana-program/stake',
    ecosystem: 'solana',
    category: 'staking',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['program', 'interface', 'README.md'],
    note: 'Native stake program (BPF port) and interface.',
  },
  {
    repo: 'solana-program/stake-pool',
    ecosystem: 'solana',
    category: 'staking',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['program', 'README.md'],
    note: 'SPL stake pool program (base of most Solana LSTs, incl. Sanctum forks).',
  },
  {
    repo: 'anza-xyz/agave',
    ecosystem: 'solana',
    category: 'client-vm',
    ref: 'v4.3',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: [
      'programs/vote/src',
      'programs/system/src',
      'programs/bpf_loader/src',
      'programs/zk-elgamal-proof/src',
      'program-runtime/src',
      'svm/src',
      'svm/doc',
      'runtime/src/bank',
      'runtime/src/bank.rs',
      'transaction-context/src',
      'poh/src',
      'entry/src',
    ],
    largeFiles: ['runtime/src/bank.rs', 'programs/vote/src/vote_state/mod.rs'],
    note: 'Validator client subset: builtin programs, SVM, program runtime, bank, PoH. Release branch v4.3 (latest stable line, v4.3.0).',
  },
  {
    repo: 'solana-labs/solana-program-library',
    ecosystem: 'solana',
    category: 'framework',
    ref: 'master',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['governance/program/src', 'token-lending/program/src', 'token-swap/program/src', 'account-compression/programs', 'docs/src', 'README.md'],
    largeFiles: ['token-swap/program/src/processor.rs'],
    note: 'Archived SPL monorepo, selected programs: governance, token-lending, token-swap, account compression.',
  },
  {
    repo: 'anza-xyz/pinocchio',
    ecosystem: 'solana',
    category: 'framework',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    note: 'Zero-dependency, zero-copy Solana program library and program bindings.',
  },

  // ─── Clients, VMs and specifications ──────────────────────────────────────
  {
    repo: 'bluealloy/revm',
    ecosystem: 'infra',
    category: 'client-vm',
    ref: 'main',
    license: 'MIT',
    tier: 'permissive',
    excludePaths: ['crates/ee-tests', 'crates/statetest-types', 'bins'],
    note: 'Rust EVM: interpreter, precompiles, handler, state.',
  },
  {
    repo: 'ethereum/go-ethereum',
    ecosystem: 'infra',
    category: 'client-vm',
    ref: 'master',
    license: 'LGPL-3.0 AND GPL-3.0',
    tier: 'copyleft',
    langs: ['go'],
    includePaths: [
      'core/vm',
      'core/state',
      'core/types',
      'core/txpool',
      'core/state_transition.go',
      'core/state_processor.go',
      'core/block_validator.go',
      'core/blockchain.go',
      'core/genesis.go',
      'consensus',
      'trie',
      'rlp',
      'params',
      'README.md',
    ],
    note: 'Geth subset: EVM, state, transactions, tx pool, consensus engines, trie, RLP. Library LGPL-3.0, binaries GPL-3.0.',
  },
  {
    repo: 'ethereum/consensus-specs',
    ecosystem: 'infra',
    category: 'client-vm',
    ref: 'master',
    license: 'CC0-1.0',
    tier: 'permissive',
    includePaths: ['specs', 'README.md'],
    note: 'Beacon chain specifications, phase0 through the latest forks (markdown with executable Python).',
  },
  {
    repo: 'ethereum/execution-specs',
    ecosystem: 'infra',
    category: 'client-vm',
    ref: 'mainnet',
    license: 'CC0-1.0',
    tier: 'permissive',
    langs: ['python'],
    includePaths: [
      'src/ethereum/forks/frontier',
      'src/ethereum/forks/london',
      'src/ethereum/forks/shanghai',
      'src/ethereum/forks/cancun',
      'src/ethereum/forks/prague',
      'src/ethereum/forks/osaka',
      'src/ethereum/crypto',
      'README.md',
    ],
    note: "Executable Python specification of the EVM and state transition, selected forks. Branch 'mainnet' (the default branch tracks the next fork and is renamed per fork).",
  },
  {
    repo: 'paradigmxyz/reth',
    ecosystem: 'infra',
    category: 'client-vm',
    ref: 'main',
    license: 'MIT OR Apache-2.0',
    tier: 'permissive',
    includePaths: [
      'crates/engine/tree',
      'crates/transaction-pool/src',
      'crates/trie/trie',
      'crates/trie/common',
      'crates/trie/sparse',
      'crates/stages/stages',
      'crates/consensus',
      'crates/ethereum/consensus',
      'crates/ethereum/evm',
      'crates/evm',
      'crates/net/eth-wire',
      'crates/net/eth-wire-types',
    ],
    largeFiles: ['crates/transaction-pool/src/pool/txpool.rs'],
    note: 'Reth subset: engine tree, tx pool, trie, staged sync, consensus, EVM config, eth wire protocol.',
  },
  {
    repo: 'sigp/lighthouse',
    ecosystem: 'infra',
    category: 'client-vm',
    ref: 'stable',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['consensus'],
    note: 'Lighthouse consensus crates: types, state processing, fork choice, proto-array.',
  },
  {
    repo: 'alloy-rs/core',
    ecosystem: 'infra',
    category: 'framework',
    ref: 'main',
    license: 'MIT OR Apache-2.0',
    tier: 'permissive',
    includePaths: ['crates', 'README.md'],
    note: 'Rust Ethereum primitives, sol! macro, ABI encoding (sol-types, dyn-abi, json-abi).',
  },
  {
    repo: 'bitcoin/bitcoin',
    ecosystem: 'bitcoin',
    category: 'client-vm',
    ref: 'v31.1',
    license: 'MIT',
    tier: 'permissive',
    includePaths: [
      'src/script',
      'src/consensus',
      'src/primitives',
      'src/policy',
      'src/kernel',
      'src/crypto',
      'src/validation.cpp',
      'src/validation.h',
      'src/net_processing.cpp',
      'src/net_processing.h',
      'src/pow.cpp',
      'src/pow.h',
      'src/chain.cpp',
      'src/chain.h',
      'src/coins.cpp',
      'src/coins.h',
      'src/txmempool.cpp',
      'src/txmempool.h',
      'src/serialize.h',
      'doc',
    ],
    excludePaths: ['doc/release-notes'],
    largeFiles: ['src/validation.cpp', 'src/net_processing.cpp'],
    note: 'Bitcoin Core subset: script interpreter, consensus, validation (ConnectBlock, AcceptToMemoryPool), P2P message processing, primitives, policy, kernel, mempool, docs. Release tag v31.1.',
  },

  // ─── Move and Cairo ───────────────────────────────────────────────────────
  {
    repo: 'MystenLabs/sui',
    ecosystem: 'move',
    category: 'framework',
    ref: 'framework/mainnet',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: [
      'crates/sui-framework/packages/sui-framework',
      'crates/sui-framework/packages/sui-system',
      'crates/sui-framework/packages/move-stdlib',
      'crates/sui-framework/packages/bridge',
    ],
    note: "Sui Move framework, system, stdlib and bridge packages as deployed on mainnet (branch 'framework/mainnet'). Archive is ~87 MB compressed.",
  },
  {
    repo: 'aptos-labs/aptos-core',
    ecosystem: 'move',
    category: 'framework',
    ref: 'mainnet',
    license: 'LicenseRef-Aptos-Innovation-Enabling',
    tier: 'source-available',
    includePaths: [
      'aptos-move/framework/aptos-framework',
      'aptos-move/framework/aptos-stdlib',
      'aptos-move/framework/move-stdlib',
      'aptos-move/framework/aptos-token-objects',
      'aptos-move/framework/aptos-token',
    ],
    largeFiles: ['aptos-move/framework/aptos-framework/sources/delegation_pool.move'],
    note: "Aptos Move framework, stdlib, token objects as deployed on mainnet (branch 'mainnet'). Innovation-Enabling Source Code License; most framework .move files have no SPDX header and are recorded under it (a few carry Apache-2.0).",
  },
  {
    repo: 'OpenZeppelin/cairo-contracts',
    ecosystem: 'cairo',
    category: 'framework',
    ref: 'main',
    license: 'MIT',
    tier: 'permissive',
    note: 'Cairo components for Starknet: tokens, accounts, governance, access, upgrades.',
  },
  {
    repo: 'starkware-libs/cairo',
    ecosystem: 'cairo',
    category: 'framework',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['corelib/src', 'README.md'],
    note: 'Cairo core library (corelib), incl. starknet module.',
  },
  {
    repo: 'starkware-libs/cairo-lang',
    ecosystem: 'cairo',
    category: 'bridge-rollup',
    ref: 'master',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['src/starkware/starknet/solidity', 'src/starkware/solidity', 'src/starkware/cairo/common', 'README.md'],
    note: 'Starknet core contracts on L1 (Solidity) and the Cairo 0 common library.',
  },

  // ─── Cosmos ───────────────────────────────────────────────────────────────
  {
    repo: 'CosmWasm/cosmwasm',
    ecosystem: 'cosmos',
    category: 'framework',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    excludePaths: ['packages/go-gen'],
    note: 'CosmWasm std, VM, crypto and example contracts.',
  },
  {
    repo: 'CosmWasm/cw-plus',
    ecosystem: 'cosmos',
    category: 'token-standard',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    note: 'cw20, cw3 multisig, cw4 group, cw1 proxies.',
  },
  {
    repo: 'cosmos/cosmos-sdk',
    ecosystem: 'cosmos',
    category: 'framework',
    ref: 'release/v0.55.x',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['x/bank', 'x/staking', 'x/auth', 'x/gov', 'x/distribution', 'x/slashing', 'x/mint', 'baseapp', 'types', 'docs/architecture'],
    note: 'SDK subset: core modules, baseapp, types, architecture decision records. Release branch v0.55.x.',
  },
  {
    repo: 'cosmos/ibc-go',
    ecosystem: 'cosmos',
    category: 'bridge-rollup',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['modules/core', 'modules/apps/transfer', 'modules/apps/27-interchain-accounts', 'modules/light-clients/07-tendermint', 'docs/docs', 'docs/architecture'],
    note: "IBC core (clients, connections, channels), ICS-20 transfer, ICS-27, Tendermint light client. Tracks 'main': the release/v* branches carry no docs/ tree.",
  },
  {
    repo: 'osmosis-labs/osmosis',
    ecosystem: 'cosmos',
    category: 'dex',
    ref: 'v31.0.3',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['x/concentrated-liquidity', 'x/gamm', 'x/poolmanager', 'x/twap', 'x/superfluid', 'osmomath'],
    note: 'Osmosis modules: concentrated liquidity (BUSL-1.1 sub-license), GAMM pools, pool manager, TWAP, superfluid. Release tag v31.0.3. Archive is ~94 MB compressed.',
  },

  // ─── Solana: protocols ────────────────────────────────────────────────────
  {
    repo: 'metaplex-foundation/mpl-token-metadata',
    ecosystem: 'solana',
    category: 'token-standard',
    ref: 'main',
    license: 'LicenseRef-Metaplex-NFT-1.0',
    tier: 'source-available',
    includePaths: ['programs/token-metadata/program', 'README.md'],
    note: 'Token Metadata program (NFT / fungible metadata, editions, programmable NFTs). Metaplex NFT Open Source License.',
  },
  {
    repo: 'metaplex-foundation/mpl-core',
    ecosystem: 'solana',
    category: 'token-standard',
    ref: 'main',
    license: 'LicenseRef-Metaplex-NFT-1.0',
    tier: 'source-available',
    includePaths: ['programs/mpl-core', 'programs/mpl-core/src/plugins/external', 'README.md'],
    note: 'Core single-account asset standard with plugins. Metaplex NFT Open Source License.',
  },
  {
    repo: 'metaplex-foundation/mpl-bubblegum',
    ecosystem: 'solana',
    category: 'token-standard',
    ref: 'main',
    license: 'LicenseRef-Metaplex-NFT-1.0',
    tier: 'source-available',
    includePaths: ['programs/bubblegum', 'README.md'],
    note: 'Compressed NFTs on concurrent Merkle trees. Metaplex NFT Open Source License.',
  },
  {
    repo: 'orca-so/whirlpools',
    ecosystem: 'solana',
    category: 'dex',
    ref: 'main',
    license: 'LicenseRef-Orca',
    tier: 'source-available',
    includePaths: ['programs/whirlpool/src', 'rust-sdk/core/src', 'README.md'],
    note: 'Whirlpools concentrated liquidity program and core math. Orca License since 2025-02-27 (Apache-2.0 before).',
  },
  {
    repo: 'raydium-io/raydium-cp-swap',
    ecosystem: 'solana',
    category: 'dex',
    ref: 'master',
    license: 'Apache-2.0',
    tier: 'permissive',
    note: 'Raydium constant-product AMM (Anchor, Token-2022 support).',
  },
  {
    repo: 'raydium-io/raydium-clmm',
    ecosystem: 'solana',
    category: 'dex',
    ref: 'master',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['programs/amm/src', 'README.md'],
    largeFiles: ['programs/amm/src/instructions/swap.rs'],
    note: 'Raydium concentrated liquidity program.',
  },
  {
    repo: 'raydium-io/raydium-amm',
    ecosystem: 'solana',
    category: 'dex',
    ref: 'master',
    license: 'Apache-2.0',
    tier: 'permissive',
    note: 'Raydium AMM v4 (native program).',
  },
  {
    repo: 'drift-labs/protocol-v2',
    ecosystem: 'solana',
    category: 'dex',
    ref: 'master',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['programs/drift/src', 'README.md'],
    note: 'Drift v2 perpetuals, spot and borrow / lend, DLOB matching, insurance fund.',
  },
  {
    repo: 'jito-foundation/jito-programs',
    ecosystem: 'solana',
    category: 'staking',
    ref: 'master',
    license: 'none',
    tier: 'unknown',
    includePaths: ['mev-programs/programs'],
    note: 'Jito tip payment, tip distribution and priority-fee distribution programs. No license file.',
  },
  {
    repo: 'jito-foundation/stakenet',
    ecosystem: 'solana',
    category: 'staking',
    ref: 'master',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['programs', 'README.md'],
    note: 'Validator history and steward programs for stake-pool delegation.',
  },
  {
    repo: 'marinade-finance/liquid-staking-program',
    ecosystem: 'solana',
    category: 'staking',
    ref: 'main',
    license: 'LicenseRef-All-Rights-Reserved',
    tier: 'source-available',
    note: 'Marinade mSOL liquid staking program. LICENSE: all rights reserved with a limited license.',
  },
  {
    repo: 'Squads-Protocol/v4',
    ecosystem: 'solana',
    category: 'wallet',
    ref: 'main',
    license: 'AGPL-3.0',
    tier: 'copyleft',
    includePaths: ['programs/squads_multisig_program/src', 'README.md'],
    note: 'Squads v4 multisig: proposals, time locks, spending limits.',
  },
  {
    repo: 'openbook-dex/openbook-v2',
    ecosystem: 'solana',
    category: 'dex',
    ref: 'master',
    license: 'MIT',
    tier: 'permissive',
    includePaths: ['programs/openbook-v2/src', 'README.md'],
    note: 'OpenBook v2 central limit order book.',
  },
  {
    repo: 'Ellipsis-Labs/phoenix-v1',
    ecosystem: 'solana',
    category: 'dex',
    ref: 'master',
    license: 'MIT',
    tier: 'permissive',
    includePaths: ['src', 'README.md'],
    note: 'Phoenix crankless on-chain order book.',
  },
  {
    repo: 'mrgnlabs/marginfi-v2',
    ecosystem: 'solana',
    category: 'lending',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['programs/marginfi/src', 'README.md'],
    note: 'marginfi v2 borrow / lend with cross-margin risk engine.',
  },
  {
    repo: 'Kamino-Finance/klend',
    ecosystem: 'solana',
    category: 'lending',
    ref: 'master',
    license: 'BUSL-1.1',
    tier: 'source-available',
    includePaths: ['programs/klend/src', 'README.md'],
    note: 'Kamino Lend reserves, obligations, liquidations, elevation groups.',
  },
  {
    repo: 'MeteoraAg/damm-v2',
    ecosystem: 'solana',
    category: 'dex',
    ref: 'main',
    license: 'LicenseRef-Meteora-Noncommercial',
    tier: 'source-available',
    includePaths: ['programs/cp-amm/src', 'README.md'],
    note: 'Meteora DAMM v2 constant-product AMM with dynamic fees (formerly MeteoraAg/cp-amm). Meteora Noncommercial Licence. The DLMM program source is not public.',
  },
  {
    repo: 'igneous-labs/S',
    ecosystem: 'solana',
    category: 'staking',
    ref: 'master',
    license: 'none',
    tier: 'unknown',
    includePaths: ['programs', 'libs/s-controller-lib/src', 'docs', 'README.md'],
    note: 'Sanctum Infinity: S controller multi-LST pool, pricing and SOL-value calculator programs. No license file.',
  },

  // ─── Move, Cairo, Bitcoin and cross-chain: protocols ──────────────────────
  {
    repo: 'MystenLabs/deepbookv3',
    ecosystem: 'move',
    category: 'dex',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['packages/deepbook/sources', 'packages/deepbook_margin/sources', 'packages/deepbook/README.md', 'packages/deepbook_margin/README.md'],
    note: 'DeepBook v3 central limit order book and margin on Sui.',
  },
  {
    repo: 'CetusProtocol/cetus-contracts',
    ecosystem: 'move',
    category: 'dex',
    ref: 'main',
    license: 'none',
    tier: 'unknown',
    note: 'Cetus CLMM on Sui: pools, tick math, positions, rewarders. No license file.',
  },
  {
    repo: 'starkware-libs/starkgate-contracts',
    ecosystem: 'cairo',
    category: 'bridge-rollup',
    ref: 'SN-v0.14.2',
    license: 'Apache-2.0',
    tier: 'permissive',
    note: 'StarkGate L1 / L2 token bridge (Solidity and Cairo).',
  },
  {
    repo: 'rust-bitcoin/rust-bitcoin',
    ecosystem: 'bitcoin',
    category: 'framework',
    ref: 'master',
    license: 'CC0-1.0',
    tier: 'permissive',
    includePaths: ['bitcoin/src', 'primitives/src', 'units/src', 'hashes/src', 'consensus_encoding/src', 'crypto/src', 'README.md'],
    note: 'Rust Bitcoin: transactions, script, taproot, PSBT, consensus encoding, hashes.',
  },
  {
    repo: 'wormhole-foundation/wormhole',
    ecosystem: 'infra',
    category: 'bridge-rollup',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: [
      'ethereum/contracts',
      'solana/bridge/program',
      'solana/modules/token_bridge/program',
      'sui/wormhole/sources',
      'sui/token_bridge/sources',
      'whitepapers',
      'README.md',
    ],
    note: 'Wormhole core and token bridge contracts (EVM, Solana, Sui) and design whitepapers.',
  },

  // ─── EVM: more protocols ──────────────────────────────────────────────────
  {
    repo: 'Layr-Labs/eigenlayer-contracts',
    ecosystem: 'evm',
    category: 'staking',
    ref: 'main',
    license: 'BUSL-1.1',
    tier: 'source-available',
    includePaths: ['src/contracts', 'docs', 'README.md'],
    note: 'EigenLayer restaking: delegation, strategies, EigenPods, slashing / allocation.',
  },
  {
    repo: 'gmx-io/gmx-synthetics',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'v2.1',
    license: 'BUSL-1.1',
    tier: 'source-available',
    includePaths: ['contracts', 'README.md'],
    excludePaths: ['contracts/mock'],
    note: "GMX v2 perpetuals and GM pools. Tag v2.1 (74.6 MB archive): 'main' is 165 MB compressed with deployment artifacts, past the archive limit.",
  },
  {
    repo: 'pendle-finance/pendle-core-v2-public',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'BUSL-1.1',
    tier: 'source-available',
    includePaths: ['contracts', 'README.md'],
    note: 'Pendle v2 yield tokenization (SY / PT / YT), PT AMM, router.',
  },
  {
    repo: 'euler-xyz/euler-vault-kit',
    ecosystem: 'evm',
    category: 'lending',
    ref: 'master',
    license: 'BUSL-1.1',
    tier: 'source-available',
    includePaths: ['src', 'src/EVault/shared/lib', 'docs', 'README.md'],
    note: 'Euler v2 EVault modules and synths. BUSL change date 2029-04-24, change license GPL-2.0-or-later.',
  },
  {
    repo: 'euler-xyz/ethereum-vault-connector',
    ecosystem: 'evm',
    category: 'lending',
    ref: 'master',
    license: 'GPL-2.0-or-later',
    tier: 'copyleft',
    includePaths: ['src', 'docs', 'README.md'],
    note: 'EVC: cross-vault collateral, batching, account status checks (used by the Euler Vault Kit).',
  },
  {
    repo: 'yearn/yearn-vaults-v3',
    ecosystem: 'evm',
    category: 'lending',
    ref: 'master',
    license: 'AGPL-3.0',
    tier: 'copyleft',
    note: 'Yearn v3 ERC-4626 allocator vaults and factory (Vyper).',
  },
  {
    repo: 'liquity/dev',
    ecosystem: 'evm',
    category: 'stablecoin',
    ref: 'main',
    license: 'GPL-3.0 AND MIT',
    tier: 'copyleft',
    includePaths: ['packages/contracts/contracts', 'README.md'],
    excludePaths: ['packages/contracts/contracts/TestContracts'],
    note: 'Liquity v1: troves, stability pool, redemptions, LQTY staking.',
  },
  {
    repo: 'liquity/bold',
    ecosystem: 'evm',
    category: 'stablecoin',
    ref: 'main',
    license: 'BUSL-1.1',
    tier: 'source-available',
    includePaths: ['contracts/src', 'README.md'],
    note: 'Liquity v2 (BOLD): user-set interest rates, multi-collateral branches.',
  },
  {
    repo: 'FraxFinance/frax-solidity',
    ecosystem: 'evm',
    category: 'stablecoin',
    ref: 'master',
    license: 'MIT',
    tier: 'permissive',
    includePaths: [
      'src/hardhat/contracts/Frax',
      'src/hardhat/contracts/FXS',
      'src/hardhat/contracts/FPI',
      'src/hardhat/contracts/Fraxswap',
      'src/hardhat/contracts/Fraxlend',
      'src/hardhat/contracts/FraxETH',
      'src/hardhat/contracts/Oracle',
      'src/hardhat/contracts/Governance',
      'README.md',
    ],
    note: 'Frax stablecoin, FXS, FPI, Fraxswap, frxETH. Files mostly GPL-2.0-or-later / MIT by SPDX header.',
  },
  {
    repo: 'Synthetixio/synthetix-v3',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'MIT',
    tier: 'permissive',
    includePaths: [
      'protocol/synthetix/contracts',
      'protocol/oracle-manager/contracts',
      'protocol/oracle-manager/contracts/interfaces/external',
      'protocol/governance/contracts',
      'markets/perps-market/contracts',
      'markets/spot-market/contracts',
      'utils/core-contracts/contracts',
      'utils/core-modules/contracts',
    ],
    note: 'Synthetix v3 core (pools, vaults, debt), oracle manager, perps and spot markets. The v2 repository is no longer public.',
  },
  {
    repo: '1inch/limit-order-protocol',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'master',
    license: 'MIT',
    tier: 'permissive',
    note: '1inch limit order protocol v4: orders, extensions, predicates.',
  },
  {
    repo: 'cowprotocol/contracts',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'LGPL-3.0-or-later',
    tier: 'copyleft',
    note: 'CoW Protocol GPv2 settlement, batch auctions, vault relayer.',
  },
  {
    repo: 'ProjectOpenSea/seaport',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'MIT',
    tier: 'permissive',
    includePaths: ['contracts', 'contracts/helpers/order-validator/lib', 'contracts/helpers/navigator/lib', 'reference', 'reference/lib', 'docs', 'README.md'],
    excludePaths: ['contracts/test'],
    note: 'Seaport marketplace: readable reference implementation, zones, order validator, docs.',
  },
  {
    repo: 'ProjectOpenSea/seaport-core',
    ecosystem: 'evm',
    category: 'dex',
    ref: 'main',
    license: 'MIT',
    tier: 'permissive',
    includePaths: ['src', 'src/lib', 'README.md'],
    note: 'Seaport 1.6 optimized core (assembly-heavy), the code deployed on chain.',
  },
  {
    repo: 'ensdomains/ens-contracts',
    ecosystem: 'evm',
    category: 'token-standard',
    ref: 'staging',
    license: 'MIT',
    tier: 'permissive',
    includePaths: ['contracts', 'README.md'],
    note: 'ENS registry, registrars, resolvers, NameWrapper, DNSSEC oracle.',
  },
  {
    repo: 'smartcontractkit/chainlink-evm',
    ecosystem: 'evm',
    category: 'oracle',
    ref: 'develop',
    license: 'MIT AND LGPL-3.0',
    tier: 'copyleft',
    includePaths: [
      'contracts/src/v0.8/shared',
      'contracts/src/v0.8/vrf',
      'contracts/src/v0.8/data-feeds',
      'contracts/src/v0.8/l2ep',
      'contracts/src/v0.8/llo-feeds/v0.5.1',
      'contracts/src/v0.8/operatorforwarder',
      'contracts/src/v0.8/payments',
    ],
    excludePaths: ['contracts/src/v0.8/vrf/testhelpers'],
    note: 'Chainlink contracts: data feeds, VRF, L2 sequencer feeds, Data Streams verifier. Files mostly MIT; Data Streams BUSL-1.1.',
  },
  {
    repo: 'ethereum-optimism/optimism',
    ecosystem: 'evm',
    category: 'bridge-rollup',
    ref: 'op-contracts/v8.0.0',
    license: 'MIT',
    tier: 'permissive',
    langs: ['go'],
    includePaths: ['packages/contracts-bedrock/src', 'packages/contracts-bedrock/src/dispute/lib', 'packages/contracts-bedrock/interfaces', 'op-node/rollup/derive'],
    note: 'OP Stack Bedrock contracts (portal, bridges, fault dispute games) and the op-node derivation pipeline. Release tag op-contracts/v8.0.0.',
  },
  {
    repo: 'OffchainLabs/nitro-contracts',
    ecosystem: 'evm',
    category: 'bridge-rollup',
    ref: 'v3.2.0',
    license: 'BUSL-1.1',
    tier: 'source-available',
    includePaths: ['src', 'README.md'],
    excludePaths: ['src/mocks', 'src/test-helpers'],
    note: 'Arbitrum Nitro rollup, bridge, one-step proofs, BoLD challenge protocol. Release tag v3.2.0.',
  },
  {
    repo: 'matter-labs/era-contracts',
    ecosystem: 'evm',
    category: 'bridge-rollup',
    ref: 'main',
    license: 'MIT',
    tier: 'permissive',
    includePaths: ['l1-contracts/contracts', 'system-contracts/contracts', 'system-contracts/bootloader', 'l2-contracts/contracts', 'da-contracts/contracts', 'system-contracts/README.md', 'l1-contracts/README.md'],
    excludePaths: ['l1-contracts/contracts/dev-contracts'],
    note: 'ZKsync L1 state transition, bridgehub, shared bridge, L2 system contracts and bootloader.',
  },
  {
    repo: 'scroll-tech/scroll-contracts',
    ecosystem: 'evm',
    category: 'bridge-rollup',
    ref: 'main',
    license: 'MIT',
    tier: 'permissive',
    includePaths: ['src', 'README.md'],
    excludePaths: ['src/test'],
    note: 'Scroll rollup, messengers, gateways, verifiers. MIT LICENSE under src/.',
  },
  {
    repo: 'agglayer/agglayer-contracts',
    ecosystem: 'evm',
    category: 'bridge-rollup',
    ref: 'main',
    license: 'AGPL-3.0',
    tier: 'copyleft',
    includePaths: ['contracts', 'contracts/lib', 'README.md'],
    excludePaths: ['contracts/previousVersions', 'contracts/mocks'],
    note: 'Polygon zkEVM / AggLayer rollup manager, unified bridge, global exit root (formerly 0xPolygonHermez/zkevm-contracts).',
  },
  {
    repo: 'across-protocol/contracts',
    ecosystem: 'evm',
    category: 'bridge-rollup',
    ref: 'master',
    license: 'BUSL-1.1',
    tier: 'source-available',
    includePaths: ['contracts', 'programs/svm-spoke/src', 'README.md'],
    excludePaths: ['contracts/test'],
    note: 'Across intents bridge: HubPool, SpokePools (EVM and Solana), chain adapters.',
  },

  // ─── Security research and reference programs ─────────────────────────────
  {
    repo: 'coral-xyz/sealevel-attacks',
    ecosystem: 'solana',
    category: 'security',
    ref: 'master',
    license: 'none',
    tier: 'unknown',
    note: 'Common Solana program vulnerabilities, insecure / secure / recommended variants. No license file.',
  },
  {
    repo: 'theredguild/damn-vulnerable-defi',
    ecosystem: 'evm',
    category: 'security',
    ref: 'master',
    license: 'MIT',
    tier: 'permissive',
    note: 'Vulnerable DeFi challenges (flash loans, oracles, governance, proxies).',
  },
  {
    repo: 'OpenZeppelin/ethernaut',
    ecosystem: 'evm',
    category: 'security',
    ref: 'master',
    license: 'AGPL-3.0',
    tier: 'copyleft',
    includePaths: ['contracts/src', 'client/src/gamedata/en'],
    note: 'Ethernaut levels and their English descriptions.',
  },
  {
    repo: 'crytic/not-so-smart-contracts',
    ecosystem: 'evm',
    category: 'security',
    ref: 'master',
    license: 'Apache-2.0',
    tier: 'permissive',
    note: 'Classic vulnerability patterns with real historical contracts (DAO, Parity, SpankChain).',
  },
  {
    repo: 'crytic/building-secure-contracts',
    ecosystem: 'evm',
    category: 'security',
    ref: 'master',
    license: 'AGPL-3.0',
    tier: 'copyleft',
    note: 'Trail of Bits guidelines, fuzzing and static-analysis guides, per-chain vulnerability catalogs.',
  },
  {
    repo: 'solana-developers/program-examples',
    ecosystem: 'solana',
    category: 'framework',
    ref: 'main',
    license: 'MIT',
    tier: 'permissive',
    note: 'Reference Solana programs in native Rust, Anchor and Pinocchio.',
  },
  {
    repo: 'SunWeb3Sec/DeFiHackLabs',
    ecosystem: 'evm',
    category: 'security',
    ref: 'main',
    license: 'Apache-2.0',
    tier: 'permissive',
    includePaths: ['src/test', 'academy', 'README.md'],
    note: 'Foundry reproductions of real DeFi exploits, 2017 to date, with write-ups.',
  },

  // ─── Specifications (text) ────────────────────────────────────────────────
  {
    repo: 'ethereum/EIPs',
    ecosystem: 'infra',
    category: 'client-vm',
    ref: 'master',
    license: 'CC0-1.0',
    tier: 'permissive',
    includePaths: ['EIPS'],
    note: 'Core, networking and interface EIPs (EIP-1559, EIP-4844, EIP-7702, …).',
  },
  {
    repo: 'ethereum/ERCs',
    ecosystem: 'evm',
    category: 'token-standard',
    ref: 'master',
    license: 'CC0-1.0',
    tier: 'permissive',
    includePaths: ['ERCS'],
    note: 'Application-level standards (ERC-20, 721, 1155, 4626, 4337, …).',
  },
]
