// Generated by scripts/tokenizer/examples.py from the protocol code index. Do not edit.
// Unmodified excerpts (whole lines, common indentation removed); license and source per entry.

export interface TokenizerExample { id: string; label: string; lang: string; repo: string; commit: string; path: string; lines: [number, number]; license: string; split: 'held-out'; code: string }

export const EXAMPLES: TokenizerExample[] = [
  {
    "id": "solmate",
    "label": "Solmate ERC4626 · deposit()",
    "lang": "solidity",
    "repo": "transmissions11/solmate",
    "commit": "89365b880c4f3c786bdd453d4b8e8fe410344a69",
    "path": "src/tokens/ERC4626.sol",
    "lines": [
      46,
      71
    ],
    "license": "AGPL-3.0-only",
    "split": "held-out",
    "code": "function deposit(uint256 assets, address receiver) public virtual returns (uint256 shares) {\n    // Check for rounding error since we round down in previewDeposit.\n    require((shares = previewDeposit(assets)) != 0, \"ZERO_SHARES\");\n\n    // Need to transfer before minting or ERC777s could reenter.\n    asset.safeTransferFrom(msg.sender, address(this), assets);\n\n    _mint(receiver, shares);\n\n    emit Deposit(msg.sender, receiver, assets, shares);\n\n    afterDeposit(assets, shares);\n}\n\nfunction mint(uint256 shares, address receiver) public virtual returns (uint256 assets) {\n    assets = previewMint(shares); // No need to check for rounding error, previewMint rounds up.\n\n    // Need to transfer before minting or ERC777s could reenter.\n    asset.safeTransferFrom(msg.sender, address(this), assets);\n\n    _mint(receiver, shares);\n\n    emit Deposit(msg.sender, receiver, assets, shares);\n\n    afterDeposit(assets, shares);\n}\n"
  },
  {
    "id": "openbook",
    "label": "OpenBook v2 · Anchor instruction",
    "lang": "rust",
    "repo": "openbook-dex/openbook-v2",
    "commit": "f3e17421e675b083b584867594bf3cf4f675d156",
    "path": "programs/openbook-v2/src/instructions/cancel_all_and_place_orders.rs",
    "lines": [
      10,
      45
    ],
    "license": "MIT",
    "split": "held-out",
    "code": "#[allow(clippy::too_many_arguments)]\npub fn cancel_all_and_place_orders<'c: 'info, 'info>(\n    ctx: Context<'_, '_, 'c, 'info, CancelAllAndPlaceOrders<'info>>,\n    cancel: bool,\n    mut orders: Vec<Order>,\n    limit: u8,\n) -> Result<Vec<Option<u128>>> {\n    let mut open_orders_account = ctx.accounts.open_orders_account.load_mut()?;\n    let open_orders_account_pk = ctx.accounts.open_orders_account.key();\n\n    let clock = Clock::get()?;\n\n    let mut market = ctx.accounts.market.load_mut()?;\n    require!(\n        !market.is_expired(clock.unix_timestamp),\n        OpenBookError::MarketHasExpired\n    );\n\n    let mut book = Orderbook {\n        bids: ctx.accounts.bids.load_mut()?,\n        asks: ctx.accounts.asks.load_mut()?,\n    };\n    let mut event_heap = ctx.accounts.event_heap.load_mut()?;\n    let event_heap_size_before = event_heap.len();\n\n    let now_ts: u64 = clock.unix_timestamp.try_into().unwrap();\n\n    let oracle_price_lots = market.oracle_price_lots(\n        AccountInfoRef::borrow_some(ctx.accounts.oracle_a.as_ref())?.as_ref(),\n        AccountInfoRef::borrow_some(ctx.accounts.oracle_b.as_ref())?.as_ref(),\n        clock.slot,\n    )?;\n\n    if cancel {\n        book.cancel_all_orders(&mut open_orders_account, *market, u8::MAX, None, None)?;\n    }\n"
  },
  {
    "id": "deepbook",
    "label": "DeepBook · math.move",
    "lang": "move",
    "repo": "MystenLabs/deepbookv3",
    "commit": "6f73d976320b3dea9697938cdcb9bebbd5ed3de2",
    "path": "packages/deepbook/sources/helper/math.move",
    "lines": [
      36,
      74
    ],
    "license": "Apache-2.0",
    "split": "held-out",
    "code": "/// Divide two floating numbers.\n/// This function will round down the result.\npublic fun div(x: u64, y: u64): u64 {\n    let (_, result) = div_internal(x, y);\n\n    result\n}\n\npublic fun div_u128(x: u128, y: u128): u128 {\n    let (_, result) = div_internal_u128(x, y);\n\n    result\n}\n\n/// Divide two floating numbers.\n/// This function will round up the result.\npublic fun div_round_up(x: u64, y: u64): u64 {\n    let (is_round_down, result) = div_internal(x, y);\n\n    result + is_round_down\n}\n\n/// given a vector of u128, return the median\npublic fun median(v: vector<u128>): u128 {\n    let n = v.length();\n    if (n == 0) {\n        return 0\n    };\n\n    let sorted_v = quick_sort(v);\n    if (n % 2 == 0) {\n        mul_u128(\n            (sorted_v[n / 2 - 1] + sorted_v[n / 2]),\n            FLOAT_SCALING_U128 / 2,\n        )\n    } else {\n        sorted_v[n / 2]\n    }\n}\n"
  },
  {
    "id": "cairo",
    "label": "OpenZeppelin Cairo · royalty_info",
    "lang": "cairo",
    "repo": "OpenZeppelin/cairo-contracts",
    "commit": "5cf9010e653b8da506f1e9824cd74c441c4f8d87",
    "path": "packages/token/src/common/erc2981/erc2981.cairo",
    "lines": [
      87,
      121
    ],
    "license": "MIT",
    "split": "held-out",
    "code": "#[embeddable_as(ERC2981Impl)]\nimpl ERC2981<\n    TContractState,\n    +HasComponent<TContractState>,\n    impl Immutable: ImmutableConfig,\n    impl SRC5: SRC5Component::HasComponent<TContractState>,\n    +Drop<TContractState>,\n> of interface::IERC2981<ComponentState<TContractState>> {\n    /// Returns how much royalty is owed and to whom, based on a sale price that may be\n    /// denominated in any unit of exchange. The royalty amount is denominated and should be\n    /// paid in that same unit of exchange.\n    ///\n    /// The returned tuple contains:\n    ///\n    /// - `t.0`: The receiver of the royalty payment.\n    /// - `t.1`: The amount of royalty payment.\n    fn royalty_info(\n        self: @ComponentState<TContractState>, token_id: u256, sale_price: u256,\n    ) -> (ContractAddress, u256) {\n        let token_royalty_info = self.ERC2981_token_royalty_info.read(token_id);\n\n        // If the token has no specific royalty info, use the default.\n        let royalty_info = if token_royalty_info.receiver.is_zero() {\n            self.ERC2981_default_royalty_info.read()\n        } else {\n            token_royalty_info\n        };\n\n        let royalty_amount = sale_price\n            * royalty_info.royalty_fraction.into()\n            / Immutable::FEE_DENOMINATOR.into();\n\n        (royalty_info.receiver, royalty_amount)\n    }\n}\n"
  }
]
