// Generated by scripts/tokenizer/examples.py from the protocol code index. Do not edit.
// Unmodified excerpts (whole lines, common indentation removed); license and source per entry.

export interface TokenizerExample { id: string; label: string; lang: string; repo: string; commit: string; path: string; lines: [number, number]; license: string; code: string }

export const EXAMPLES: TokenizerExample[] = [
  {
    "id": "uniswap",
    "label": "Uniswap V2 · swap()",
    "lang": "solidity",
    "repo": "Uniswap/v2-core",
    "commit": "6a9e7c97860676e0992f22a49665760444c1cdf5",
    "path": "contracts/UniswapV2Pair.sol",
    "lines": [
      158,
      187
    ],
    "license": "GPL-3.0",
    "code": "// this low-level function should be called from a contract which performs important safety checks\nfunction swap(uint amount0Out, uint amount1Out, address to, bytes calldata data) external lock {\n    require(amount0Out > 0 || amount1Out > 0, 'UniswapV2: INSUFFICIENT_OUTPUT_AMOUNT');\n    (uint112 _reserve0, uint112 _reserve1,) = getReserves(); // gas savings\n    require(amount0Out < _reserve0 && amount1Out < _reserve1, 'UniswapV2: INSUFFICIENT_LIQUIDITY');\n\n    uint balance0;\n    uint balance1;\n    { // scope for _token{0,1}, avoids stack too deep errors\n    address _token0 = token0;\n    address _token1 = token1;\n    require(to != _token0 && to != _token1, 'UniswapV2: INVALID_TO');\n    if (amount0Out > 0) _safeTransfer(_token0, to, amount0Out); // optimistically transfer tokens\n    if (amount1Out > 0) _safeTransfer(_token1, to, amount1Out); // optimistically transfer tokens\n    if (data.length > 0) IUniswapV2Callee(to).uniswapV2Call(msg.sender, amount0Out, amount1Out, data);\n    balance0 = IERC20(_token0).balanceOf(address(this));\n    balance1 = IERC20(_token1).balanceOf(address(this));\n    }\n    uint amount0In = balance0 > _reserve0 - amount0Out ? balance0 - (_reserve0 - amount0Out) : 0;\n    uint amount1In = balance1 > _reserve1 - amount1Out ? balance1 - (_reserve1 - amount1Out) : 0;\n    require(amount0In > 0 || amount1In > 0, 'UniswapV2: INSUFFICIENT_INPUT_AMOUNT');\n    { // scope for reserve{0,1}Adjusted, avoids stack too deep errors\n    uint balance0Adjusted = balance0.mul(1000).sub(amount0In.mul(3));\n    uint balance1Adjusted = balance1.mul(1000).sub(amount1In.mul(3));\n    require(balance0Adjusted.mul(balance1Adjusted) >= uint(_reserve0).mul(_reserve1).mul(1000**2), 'UniswapV2: K');\n    }\n\n    _update(balance0, balance1, _reserve0, _reserve1);\n    emit Swap(msg.sender, amount0In, amount1In, amount0Out, amount1Out, to);\n}\n"
  },
  {
    "id": "anchor",
    "label": "Anchor · swap_base_input",
    "lang": "rust",
    "repo": "raydium-io/raydium-cp-swap",
    "commit": "b3187ae53a1b95a201f855a59024a12ca8f5b51a",
    "path": "programs/cp-swap/src/instructions/swap_base_input.rs",
    "lines": [
      75,
      108
    ],
    "license": "Apache-2.0",
    "code": "pub fn swap_base_input(ctx: Context<Swap>, amount_in: u64, minimum_amount_out: u64) -> Result<()> {\n    let block_timestamp = solana_program::clock::Clock::get()?.unix_timestamp as u64;\n    let pool_id = ctx.accounts.pool_state.key();\n    let pool_state = &mut ctx.accounts.pool_state.load_mut()?;\n    if !pool_state.get_status_by_bit(PoolStatusBitIndex::Swap)\n        || block_timestamp < pool_state.open_time\n    {\n        return err!(ErrorCode::NotApproved);\n    }\n\n    let transfer_fee =\n        get_transfer_fee(&ctx.accounts.input_token_mint.to_account_info(), amount_in)?;\n    // Take transfer fees into account for actual amount transferred in\n    let actual_amount_in = amount_in.saturating_sub(transfer_fee);\n    require_gt!(actual_amount_in, 0);\n\n    let SwapParams {\n        trade_direction,\n        total_input_token_amount,\n        total_output_token_amount,\n        token_0_price_x64,\n        token_1_price_x64,\n        is_creator_fee_on_input,\n    } = pool_state.get_swap_params(\n        ctx.accounts.input_vault.key(),\n        ctx.accounts.output_vault.key(),\n        ctx.accounts.input_vault.amount,\n        ctx.accounts.output_vault.amount,\n    )?;\n    let constant_before = u128::from(total_input_token_amount)\n        .checked_mul(u128::from(total_output_token_amount))\n        .unwrap();\n\n    let creator_fee_rate =\n"
  },
  {
    "id": "move",
    "label": "Sui Move · coin",
    "lang": "move",
    "repo": "MystenLabs/sui",
    "commit": "782577ca40c9ef0b3f400ade8bc2cc2dcd0e2b23",
    "path": "crates/sui-framework/packages/sui-framework/sources/coin.move",
    "lines": [
      184,
      208
    ],
    "license": "Apache-2.0",
    "code": "/// Consume the coin `c` and add its value to `self`.\n/// Aborts if `c.value + self.value > U64_MAX`\npublic entry fun join<T>(self: &mut Coin<T>, c: Coin<T>) {\n    let Coin { id, balance } = c;\n    id.delete();\n    self.balance.join(balance);\n}\n\n/// Split coin `self` to two coins, one with balance `split_amount`,\n/// and the remaining balance is left is `self`.\npublic fun split<T>(self: &mut Coin<T>, split_amount: u64, ctx: &mut TxContext): Coin<T> {\n    take(&mut self.balance, split_amount, ctx)\n}\n\n/// Split coin `self` into `n - 1` coins with equal balances. The remainder is left in\n/// `self`. Return newly created coins.\npublic fun divide_into_n<T>(self: &mut Coin<T>, n: u64, ctx: &mut TxContext): vector<Coin<T>> {\n    assert!(n > 0, EInvalidArg);\n    assert!(n <= self.value(), ENotEnough);\n\n    let split_amount = self.value() / n;\n    vector::tabulate!(n - 1, |_| self.split(split_amount, ctx))\n}\n\n/// Make any Coin with a zero value. Useful for placeholding\n"
  },
  {
    "id": "cairo",
    "label": "Cairo · ERC20 transfer",
    "lang": "cairo",
    "repo": "OpenZeppelin/cairo-contracts",
    "commit": "5cf9010e653b8da506f1e9824cd74c441c4f8d87",
    "path": "packages/token/src/erc20/erc20.cairo",
    "lines": [
      142,
      173
    ],
    "license": "MIT",
    "code": "/// Moves `amount` tokens from the caller's token balance to `to`.\n///\n/// Requirements:\n///\n/// - `recipient` is not the zero address.\n/// - The caller has a balance of at least `amount`.\n///\n/// Emits a `Transfer` event.\nfn transfer(\n    ref self: ComponentState<TContractState>, recipient: ContractAddress, amount: u256,\n) -> bool {\n    let sender = starknet::get_caller_address();\n    self._transfer(sender, recipient, amount);\n    true\n}\n\n/// Moves `amount` tokens from `from` to `to` using the allowance mechanism.\n/// `amount` is then deducted from the caller's allowance.\n///\n/// Requirements:\n///\n/// - `sender` is not the zero address.\n/// - `sender` must have a balance of at least `amount`.\n/// - `recipient` is not the zero address.\n/// - The caller has an allowance of `sender`'s tokens of at least `amount`.\n///\n/// Emits a `Transfer` event.\nfn transfer_from(\n    ref self: ComponentState<TContractState>,\n    sender: ContractAddress,\n    recipient: ContractAddress,\n    amount: u256,\n"
  }
]
