// ADVISORY CHECK: every kept EVM contract's stored Solidity sources checked against every published OpenZeppelin
// Contracts security advisory and the known bugs of its exact solc version.
//
// Zero RPC, zero registry calls: reads only the chain store's kept records (source texts) and the vendored data in
// server/advisory/data (regenerated by scripts/advisory/*). Computed in the background, one record at a time, off the
// request path; results persist in <data>/advisory/state.json (well under 2 MB) and are recomputed when a kept item is
// re-read or when the data / matcher changes.
//
// REST (shared/advisory.ts): /api/advisories/summary, /api/advisories/items, /api/advisories/:chain/:address
import fs from 'node:fs'
import path from 'node:path'
import type { ChainId, ChainIndexItem } from '../../shared/chain.ts'
import { ADVISORY_SCOPE, COMPILER_SCOPE, type AdvisoryItem, type AdvisoryList, type AdvisoryListItem, type AdvisorySummary } from '../../shared/advisory.ts'
import { cmpVer } from './core.ts'
import { loadDataset, type Dataset } from './dataset.ts'
import { checkSources, type CheckResult } from './match.ts'

type Log = (lvl: 'info' | 'warn' | 'error', msg: string) => void

export interface AdvisorySource {
  items(q: { chain?: ChainId; limit?: number; cursor?: string }): { items: ChainIndexItem[]; next: string | null }
  /** Stored source texts + compiler of one kept item (null when the record is gone). */
  record(chain: ChainId, address: string): Promise<{ sources: { path: string; text: string }[]; compiler: string | null } | null>
}

export interface AdvisoryOptions {
  source: AdvisorySource
  dataDir: string
  log: Log
  dataset?: Dataset
  /** Look for newly kept / re-read items this often, ms. */
  refreshMs?: number
  startDelayMs?: number
  /** Most items listed per page of /items. */
  pageSize?: number
}

/** Persisted per item: what was checked and the result. */
interface Entry { chain: ChainId; address: string; name: string | null; readAt: number; firstSeen: number; checkedAt: number; r: CheckResult | null; skip?: 'no-source' | 'vyper' }

export interface AdvisoryCheck {
  start(): void
  stop(): Promise<void>
  /** Check everything new or re-read now (tests, tools). Resolves when done. */
  refresh(): Promise<void>
  summary(): AdvisorySummary
  list(q: { advisory?: string; bug?: string; chain?: ChainId; cursor?: string; limit?: number }): AdvisoryList | null
  get(chain: ChainId, address: string): AdvisoryItem | null
  /** /api/advisories/* → JSON (validated, cached by result version). */
  route(p: string, params: URLSearchParams): { status: number; json: string; headers?: Record<string, string> }
}

const keyOf = (chain: ChainId, address: string) => `${chain}:${chain === 'solana' ? address : address.toLowerCase()}`
const CHAINS = new Set<ChainId>(['ethereum', 'base', 'arbitrum'])
const sevOrder: Record<string, number> = { high: 0, 'medium/high': 1, medium: 2, 'low/medium': 3, low: 4, 'very low': 5 }

export function createAdvisoryCheck(o: AdvisoryOptions): AdvisoryCheck {
  const log = o.log
  const ds = o.dataset ?? loadDataset()
  const dir = path.join(o.dataDir, 'advisory')
  const file = path.join(dir, 'state.json')
  const refreshMs = o.refreshMs ?? 60_000
  const pageSize = Math.max(1, Math.min(100, o.pageSize ?? 50))
  const entries = new Map<string, Entry>()
  let solana = 0
  let version = 0
  let running: Promise<void> | null = null
  let progress = { done: 0, total: 0 }
  let timer: NodeJS.Timeout | null = null
  let startTimer: NodeJS.Timeout | null = null
  let stopped = false
  let dirty = false
  let lastSave = 0
  const advById = new Map(ds.info.map((a) => [a.id, a]))
  const bugByName = new Map(ds.solc.bugs.map((b, i) => [b.name, i]))

  // ── persistence ──
  try {
    const j = JSON.parse(fs.readFileSync(file, 'utf8')) as { v: number; data: string; entries: Entry[]; solana?: number }
    if (j?.v === 1 && j.data === ds.version && Array.isArray(j.entries)) {
      for (const e of j.entries) entries.set(keyOf(e.chain, e.address), e)
      // until the first pass after a restart, report what the last pass saw
      progress = { done: entries.size, total: entries.size }
      solana = typeof j.solana === 'number' ? j.solana : 0
    }
    else if (j) log('info', 'advisory: data or matcher changed; every kept contract is checked again')
  } catch { /* first boot */ }

  function save(force = false) {
    if (!dirty || (!force && Date.now() - lastSave < 10_000)) return
    try {
      fs.mkdirSync(dir, { recursive: true })
      const tmp = `${file}.tmp`
      fs.writeFileSync(tmp, JSON.stringify({ v: 1, data: ds.version, savedAt: Date.now(), solana, entries: [...entries.values()] }))
      fs.renameSync(tmp, file)
      dirty = false
      lastSave = Date.now()
    } catch (e) {
      log('warn', `advisory: save failed: ${(e as Error)?.message ?? e}`)
    }
  }

  function listAll(): ChainIndexItem[] {
    const out: ChainIndexItem[] = []
    let cursor: string | undefined
    for (let guard = 0; guard < 2000; guard++) {
      const page = o.source.items({ limit: 200, cursor })
      out.push(...page.items)
      if (!page.next) break
      cursor = page.next
    }
    return out
  }

  const yieldLoop = () => new Promise<void>((r) => setImmediate(r))

  async function run() {
    const t0 = Date.now()
    const all = listAll()
    const sol = all.filter((it) => it.chain === 'solana').length
    if (sol !== solana) { solana = sol; dirty = true; version++ }
    const evm = all.filter((it) => CHAINS.has(it.chain))
    const live = new Set(evm.map((it) => keyOf(it.chain, it.address)))
    for (const k of [...entries.keys()]) if (!live.has(k)) { entries.delete(k); dirty = true }
    const todo = evm.filter((it) => { const e = entries.get(keyOf(it.chain, it.address)); return !e || e.readAt !== it.readAt })
    progress = { done: evm.length - todo.length, total: evm.length }
    let checked = 0
    for (const it of todo) {
      if (stopped) break
      const k = keyOf(it.chain, it.address)
      let rec: Awaited<ReturnType<AdvisorySource['record']>> = null
      try { rec = await o.source.record(it.chain, it.address) } catch (e) { log('warn', `advisory: record ${it.address.slice(0, 10)}… unreadable: ${(e as Error)?.message ?? e}`) }
      const base = { chain: it.chain, address: it.address, name: it.name, readAt: it.readAt, firstSeen: it.firstSeen, checkedAt: Date.now() }
      if (!rec) {
        entries.set(k, { ...base, r: null, skip: 'no-source' })
        dirty = true
        progress.done++
        continue
      }
      const sol = rec.sources.filter((s) => /\.sol$/i.test(s.path))
      if (!sol.length) {
        const vy = rec.sources.some((s) => /\.vyi?$/i.test(s.path)) || /vyper/i.test(rec.compiler ?? '')
        entries.set(k, { ...base, r: null, skip: vy ? 'vyper' : 'no-source' })
      } else {
        try {
          entries.set(k, { ...base, r: checkSources(ds, rec.sources, rec.compiler) })
        } catch (e) {
          log('warn', `advisory: check ${it.address.slice(0, 10)}… failed: ${(e as Error)?.message ?? e}`)
        }
      }
      dirty = true
      checked++
      progress.done++
      if (checked % 25 === 0) { version++; save() }
      await yieldLoop()
    }
    if (checked) {
      version++
      save(true)
      log('info', `advisory: checked ${checked} contracts in ${((Date.now() - t0) / 1000).toFixed(1)} s (${entries.size} on record)`)
    } else if (dirty) { version++; save(true) }
  }

  function refresh(): Promise<void> {
    if (stopped) return Promise.resolve()
    if (!running) running = run().catch((e) => log('warn', `advisory: refresh failed: ${(e as Error)?.message ?? e}`)).finally(() => { running = null })
    return running
  }

  // ── read side (cached per result version) ──
  let summaryCache: { v: number; at: number; s: AdvisorySummary; json: string } | null = null
  function summary(): AdvisorySummary {
    if (summaryCache && summaryCache.v === version && (!running || Date.now() - summaryCache.at < 2_000)) return summaryCache.s
    let checked = 0, noSource = 0, vyper = 0, withOz = 0, ozFiles = 0, withAdv = 0, known = 0, withBugs = 0
    const byChain: Record<string, number> = {}
    const perAdv = new Map<string, { contracts: number; hash: number; header: number }>()
    const rel = new Map<string, number>()
    const bySeverity: Record<string, number> = {}
    const bugCount = new Map<number, number>()
    const verCount = new Map<string, number>()
    for (const e of entries.values()) {
      if (e.skip === 'no-source') { noSource++; continue }
      if (e.skip === 'vyper') { vyper++; continue }
      const r = e.r
      if (!r) continue
      checked++
      byChain[e.chain] = (byChain[e.chain] ?? 0) + 1
      if (r.ozFiles) { withOz++; ozFiles += r.ozFiles }
      if (r.advisories.length) withAdv++
      for (const a of r.advisories) {
        const c = perAdv.get(a.id) ?? { contracts: 0, hash: 0, header: 0 }
        c.contracts++
        if (a.files.some((f) => f.method === 'hash')) c.hash++
        else c.header++
        perAdv.set(a.id, c)
      }
      for (const z of r.ozReleases) if (z.label) rel.set(`${z.pkg}\n${z.label}`, (rel.get(`${z.pkg}\n${z.label}`) ?? 0) + 1)
      if (r.solc) {
        known++
        verCount.set(r.solc.version, (verCount.get(r.solc.version) ?? 0) + 1)
        if (r.solc.bugs.length) withBugs++
        const sevs = new Set<string>()
        for (const b of r.solc.bugs) { bugCount.set(b, (bugCount.get(b) ?? 0) + 1); sevs.add(ds.solc.bugs[b].severity) }
        for (const s of sevs) bySeverity[s] = (bySeverity[s] ?? 0) + 1
      }
    }
    const s: AdvisorySummary = {
      updatedAt: Date.now(),
      progress: { done: progress.done, total: progress.total, running: !!running },
      checked,
      notChecked: { noSource, vyper, solana },
      byChain,
      withOz,
      ozFiles,
      withAdvisoryFile: withAdv,
      advisories: ds.info.map((a) => { const c = perAdv.get(a.id) ?? { contracts: 0, hash: 0, header: 0 }; return { ...a, contracts: c.contracts, byMethod: { hash: c.hash, header: c.header } } }),
      topReleases: [...rel.entries()].map(([k, n]) => { const [pkg, label] = k.split('\n'); return { pkg, label, contracts: n } }).sort((a, b) => b.contracts - a.contracts || cmpVer(b.label.split(' ')[0], a.label.split(' ')[0])).slice(0, 10),
      compiler: {
        known,
        withBugs,
        bySeverity,
        bugs: [...bugCount.entries()].map(([i, n]) => { const b = ds.solc.bugs[i]; return { name: b.name, severity: b.severity, summary: b.summary, link: b.link, conditions: b.conditions, contracts: n } })
          .sort((a, b) => (sevOrder[a.severity] ?? 9) - (sevOrder[b.severity] ?? 9) || b.contracts - a.contracts || a.name.localeCompare(b.name)),
        versions: [...verCount.entries()].map(([version, contracts]) => ({ version, contracts })).sort((a, b) => cmpVer(b.version, a.version)),
      },
      data: {
        ozVersions: ds.fp.stats.versions,
        ozUniqueFiles: ds.fp.stats.uniqueFiles,
        fingerprintsAt: ds.fp.generatedAt,
        advisoriesReviewedAt: ds.advisories.reviewedAt,
        solcBugs: ds.solc.bugs.length,
        solcBugsAt: ds.solc.generatedAt,
        packages: ds.fp.packages.map((p) => p.name),
      },
      scope: ADVISORY_SCOPE,
      compilerScope: COMPILER_SCOPE,
    }
    summaryCache = { v: version, at: Date.now(), s, json: JSON.stringify(s) }
    return s
  }

  /** Newest kept first (firstSeen desc, then key) — a stable order for cursors. */
  function sorted(): Entry[] {
    return [...entries.values()].filter((e) => e.r).sort((a, b) => b.firstSeen - a.firstSeen || keyOf(a.chain, a.address).localeCompare(keyOf(b.chain, b.address)))
  }
  let sortedCache: { v: number; list: Entry[] } | null = null

  function list(q: { advisory?: string; bug?: string; chain?: ChainId; cursor?: string; limit?: number }): AdvisoryList | null {
    if (q.advisory && !advById.has(q.advisory)) return null
    const bugIdx = q.bug ? bugByName.get(q.bug) : undefined
    if (q.bug && bugIdx === undefined) return null
    if (!sortedCache || sortedCache.v !== version) sortedCache = { v: version, list: sorted() }
    const limit = Math.max(1, Math.min(pageSize, q.limit ?? pageSize))
    const match = sortedCache.list.filter((e) => {
      if (q.chain && e.chain !== q.chain) return false
      const r = e.r!
      if (q.advisory) return r.advisories.some((a) => a.id === q.advisory)
      if (bugIdx !== undefined) return !!r.solc?.bugs.includes(bugIdx)
      return r.advisories.length > 0
    })
    const start = q.cursor ? Math.max(0, Number(q.cursor) || 0) : 0
    const page = match.slice(start, start + limit)
    const items: AdvisoryListItem[] = page.map((e) => ({
      chain: e.chain,
      address: e.address,
      name: e.name,
      files: q.advisory ? e.r!.advisories.find((a) => a.id === q.advisory)!.files : [],
      solc: e.r!.solc?.version ?? null,
      advisories: e.r!.advisories.length,
    }))
    return { items, next: start + limit < match.length ? String(start + limit) : null, total: match.length, scope: ADVISORY_SCOPE }
  }

  function get(chain: ChainId, address: string): AdvisoryItem | null {
    const e = entries.get(keyOf(chain, address))
    if (!e) return null
    const notes: string[] = []
    if (e.skip === 'no-source') notes.push('no Solidity source is stored for this contract, so nothing was checked')
    if (e.skip === 'vyper') notes.push('Vyper contract: OpenZeppelin Contracts advisories and the Solidity compiler bug list do not apply')
    const r = e.r
    return {
      chain: e.chain,
      address: e.address,
      name: e.name,
      checkedAt: e.checkedAt,
      files: r?.files ?? 0,
      ozFiles: r?.ozFiles ?? 0,
      ozReleases: r?.ozReleases ?? [],
      advisories: (r?.advisories ?? []).map((a) => {
        const info = advById.get(a.id)!
        const pk = info.packages.find((p) => p.name === a.files[0]?.pkg) ?? info.packages[0]
        return { ...a, title: info.title, url: info.url, aliases: info.aliases, label: pk ? `${pk.label}${pk.fixedIn.length ? ` · fixed in ${pk.fixedIn.join(' / ')}` : ''}` : '' }
      }),
      solc: r?.solc ? { version: r.solc.version, compiler: r.solc.compiler, released: ds.solc.versions[r.solc.version]?.released ?? null, bugs: r.solc.bugs.map((i) => ds.solc.bugs[i]).sort((a, b) => (sevOrder[a.severity] ?? 9) - (sevOrder[b.severity] ?? 9) || a.name.localeCompare(b.name)) } : null,
      notes: [...notes, ...(r?.notes ?? [])],
      scope: ADVISORY_SCOPE,
      compilerScope: COMPILER_SCOPE,
    }
  }

  // ── HTTP ──
  const CACHE = { 'Cache-Control': 'public, max-age=15' }
  const lru = new Map<string, string>()
  const remember = (k: string, json: string) => { lru.set(k, json); if (lru.size > 600) lru.delete(lru.keys().next().value as string); return json }
  const err = (status: number, error: string) => ({ status, json: JSON.stringify({ error }) })

  function route(p: string, params: URLSearchParams): { status: number; json: string; headers?: Record<string, string> } {
    if (p === '/api/advisories/summary') {
      summary()
      return { status: 200, json: summaryCache!.json, headers: CACHE }
    }
    if (p === '/api/advisories/items') {
      const advisory = params.get('advisory') || ''
      const bug = params.get('bug') || ''
      const chain = params.get('chain') || ''
      const cursor = params.get('cursor') || ''
      const limitRaw = params.get('limit') || ''
      if (limitRaw && !/^\d{1,3}$/.test(limitRaw)) return err(400, `limit must be a number from 1 to ${pageSize}`)
      const limit = limitRaw ? Math.max(1, Math.min(pageSize, Number(limitRaw))) : pageSize
      if (advisory && !/^GHSA(-[23456789cfghjmpqrvwx]{4}){3}$/.test(advisory)) return err(400, 'advisory must be a GHSA id listed in /api/advisories/summary')
      if (bug && !/^[A-Za-z0-9]{3,80}$/.test(bug)) return err(400, 'bug must be a Solidity bug name listed in /api/advisories/summary')
      if (advisory && bug) return err(400, 'ask for one advisory or one compiler bug')
      if (chain && !CHAINS.has(chain as ChainId)) return err(400, 'chain must be ethereum, base or arbitrum')
      if (cursor && !/^\d{1,6}$/.test(cursor)) return err(400, 'cursor is not one this server issued')
      const k = `items:${version}:${advisory}:${bug}:${chain}:${cursor}:${limit}`
      const hit = lru.get(k)
      if (hit) return { status: 200, json: hit, headers: CACHE }
      const l = list({ advisory: advisory || undefined, bug: bug || undefined, chain: (chain || undefined) as ChainId | undefined, cursor: cursor || undefined, limit })
      if (!l) return err(404, advisory ? 'no advisory with this id' : 'no compiler bug with this name')
      return { status: 200, json: remember(k, JSON.stringify(l)), headers: CACHE }
    }
    const m = /^\/api\/advisories\/(ethereum|base|arbitrum|solana)\/([A-Za-z0-9]{20,64})$/.exec(p)
    if (!m) return err(404, 'not found')
    if (m[1] === 'solana') return err(404, 'Solana programs are not Solidity: the advisory check covers EVM contracts')
    if (!/^0x[0-9a-fA-F]{40}$/.test(m[2])) return err(400, 'address must be a 0x EVM address')
    const k = `item:${version}:${keyOf(m[1] as ChainId, m[2])}`
    const hit = lru.get(k)
    if (hit) return { status: 200, json: hit, headers: CACHE }
    const it = get(m[1] as ChainId, m[2])
    if (!it) return err(404, running ? 'not checked yet: the check is running' : 'this contract is not among the kept contracts')
    return { status: 200, json: remember(k, JSON.stringify(it)), headers: CACHE }
  }

  return {
    start() {
      if (timer || stopped) return
      startTimer = setTimeout(() => {
        void refresh()
        timer = setInterval(() => void refresh(), refreshMs)
        timer.unref?.()
      }, o.startDelayMs ?? 10_000)
      startTimer.unref?.()
    },
    async stop() {
      stopped = true
      if (startTimer) clearTimeout(startTimer)
      if (timer) clearInterval(timer)
      await running?.catch(() => {})
      save(true)
    },
    refresh,
    summary,
    list,
    get,
    route,
  }
}
